### ISSUE TITLE
Future should return counter variable ownership

### ISSUE THREAD

**Issue by soundprojects** [soundprojects/trainsim#3]
I changed my main function to print the final count (10 at the end of the program). The count is passed to our future by using the move keyword. This should give ownership of a reference of count to our function according to documentation.

I await the task using` let _result = task.await.unwrap(); ` but when I run the program the output is '0'

Why is this? This should run synchronously and our `move` keyword is not a clone of our variable. The compiler does not see any ownership issues so when the future is done running, our ownership should return and our count should be 10..?
```
//Tokio::main macro translates the main function back to a non-async function
// .await calls are transformed to block_on to make for easy coding
#[tokio::main]
async fn main() {
    let mut counter: i32 = 0;

    let input_task = tokio::spawn(async{
        read_input().await;
    });

    let task = tokio::spawn(async move {
        run_timer(&mut counter).await;
        
    });

    //block on our task
    let _result = task.await.unwrap(); 
    println!("Count is: {}", counter);

}
```

**Comment by ruurdadema** [comment]
I think it might be copying instead of moving counter because it is a POD (plain old data) type. You can read about that [here](https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html#the-string-type).  

So what I *think* is happening is that counter gets copied into the closure of task where you pass a mutable reference to this copy of counter to run_timer.

You might get some hint by adding the print statement in to the closure of task:

```
let task = tokio::spawn(async move {
    run_timer(&mut counter).await;
    println!("Count is: {}", counter);
});
```

Could you point me to a specific commit (or branch) with runnable code so I can have a look? You're already touching stuff which I don't have very much experience in with using Rust :-)

**Comment by soundprojects** [comment]
Latest commit on development branch shows this issue. When I put the `println!` inside the closure, count is 10.

**Comment by ruurdadema** [comment]
Have a look [here](https://github.com/soundprojects/trainsim/commit/aa8978861baec34b933a677fafd848b2dfc591cb) to see how you might solve it.

**Comment by soundprojects** [comment]
So I understand the end result of counter needing to be an atomic operation within an Arc. I don't understand why yet.

My code seems to be synchronous as we block on our timer calls, wait for them to finish and only then do we continue on our main thread. If we are referencing the same variable, how can this be different?

**Comment by ruurdadema** [comment]
To 'prove' correct behaviour of the program we need to ensure 2 things:

- The counter must not go out of scope before the task `task` finishes. We do this by the Arc (atomic reference counter), which will keep the object alive for as long as there is at least one reference to it. The reference counting must be atomic because the reference count itself may be accessed from different threads. If we wouldn't use the Arc, then the counter variable would be moved into the async {} block which makes the counter unavailable for printing after all tasks have finished `println!("Count is: {}", counter.load(Ordering::SeqCst));`

-  The counter value itself is going to be accessed by different threads and thus needs to have some synchronisation. The way to do this for complex types is to add a Mutex, but for simple types we can just grab an atomic type.

Does this make sense?

btw. I like the slint markup language

**Comment by ruurdadema** [comment]
See [this](https://github.com/soundprojects/trainsim/commit/791025aa66c13f2fd155050183789cd9b117d572) commit for a simplification, although I realise that this might not be what you're trying to simulate.

**Comment by soundprojects** [comment]
Almost got it. I'll save this for a video talk so I can ask about some specifics.

**Comment by soundprojects** [comment]
Because plain old datatypes are smaller than the pointer asked for by the move operation, a copy of counter is made.
